# Generated by Django 4.1.1 on 2022-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=30)),
                ('lastname_user', models.CharField(max_length=30)),
                ('email_user', models.EmailField(max_length=50)),
                ('password_user', models.CharField(max_length=30)),
            ],
        ),
    ]
