# Generated by Django 4.1.1 on 2022-09-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_crop', models.ImageField(upload_to='image_crops')),
                ('name_crop', models.CharField(max_length=30)),
                ('name_scie_crop', models.CharField(max_length=30)),
                ('description_crop', models.TextField(max_length=600)),
                ('time_germination', models.PositiveSmallIntegerField()),
                ('time_harvest', models.PositiveSmallIntegerField(default=8)),
                ('time_seeding', models.CharField(max_length=15)),
                ('time_sun_crop', models.CharField(max_length=20)),
                ('amount_water_crop', models.CharField(max_length=30)),
                ('distance_crops', models.PositiveSmallIntegerField()),
                ('height_max_crop', models.PositiveSmallIntegerField()),
                ('type_container', models.CharField(choices=[('Ma', 'Macetas'), ('Mc', 'Mesas de cultivos'), ('Jv', 'Jardineras Verticales')], default='Ma', max_length=30)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
