# Generated by Django 4.1.1 on 2022-09-12 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pest', models.CharField(max_length=20)),
                ('description_pest', models.TextField(max_length=500)),
                ('photo_pest', models.ImageField(upload_to='image_pests')),
                ('description_prevent', models.TextField(max_length=600)),
                ('id_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
            ],
        ),
    ]
